apiVersion: v1
kind: Service
metadata:
  name: satellite-images-model-service
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: satellite-images-model-deployment
