apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kindlytoad
spec:
  serviceName: "kindlytoad"
  selector:
    matchLabels:
      app: kindlytoad
  replicas: 1
  template:
    metadata:
      labels:
        app: kindlytoad
    spec:
      volumes:
        - name: volumepartage
          persistentVolumeClaim:
            claimName: espace-kindlytoad
      containers:
        - name: geoserver
          image: kartoza/geoserver:2.19.0 # 2.19.0
          imagePullPolicy: Always
          # env:
          # - name: GEOSERVER_ADMIN_USER
          #   value: admin
          # - name: GEOSERVER_ADMIN_PASSWORD
          #   value: admin
          volumeMounts: # This section specifies where the volume should be mounted inside the container
            - name: volumepartage
              mountPath: /opt/geoserver/data_dir/bibi/ # Replace this with the actual moun #/opt/geoserver_data

      initContainers:
        - name: downloadimages
          image: minio/mc
          imagePullPolicy: Always
         
          command: ["mc"]
          args: ["cp","s3/cguillo/ilots_972.gpkg","dossierimage/ilots_972.gpkg"]
          envFrom:
          - secretRef:
              name: env-secrets-kindlytoad
          # On copie une image dans le volume en passant par le dossier img créé dans l'init docker pour l'occasion.
          volumeMounts:
            - mountPath: /dossierimage
              name: volumepartage 