apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-geoserver
  namespace: projet-slums-detection
data:
  GEOSERVER_CSRF_DISABLED: "true"
  INSTALL_EXTENSIONS: "true"
  COMMUNITY_EXTENSIONS: cog-plugin
  STABLE_EXTENSIONS: gwc-s3-plugin
  ACTIVATE_ALL_STABLE_EXTENSIONS: "false"
  ACTIVATE_ALL_COMMUNITY_EXTENSIONS: "false"
