apiVersion: v1
kind: Service
metadata:
  name: geoserver-instance
spec:
  type: ClusterIP
  ports:
    - name: http-geoserver
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: geoserver-instance
