apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: geoserver-instance
spec:
  serviceName: "geoserver-instance"
  replicas: 1
  selector:
    matchLabels:
      app: geoserver-instance
  template:
    metadata:
      labels:
        app: geoserver-instance
    spec:
      # initContainers:
      #   - name: install-extensions
      #     image: minio/mc
      #     command: ["/bin/sh", "-c"]
      #     args:
      #       - |
      #         mc cp --recursive s3/projet-slums-detection/data-geoserver/geoserver-2.23-SNAPSHOT-cog-plugin/ /geoserver-extensions/

      #     envFrom:
      #     - secretRef:
      #         name: env-secrets-slums-detection
      #     volumeMounts:
      #       - name: geoserver-extensions
      #         mountPath: /geoserver-extensions
      containers:
        - name: geoserver
          image: kartoza/geoserver:2.25.0
          imagePullPolicy: Always
          env:
            - name: GEOSERVER_ADMIN_USER
              value: "admin"
            - name: GEOSERVER_ADMIN_PASSWORD
              value: "admin"
            - name: GEOSERVER_CSRF_DISABLED
              value: "true"
            - name: INSTALL_EXTENSIONS
              value: "true"
            - name: COMMUNITY_EXTENSIONS
              value: "cog-plugins"

          # ports:
          #   - name: http-geoserver
          #     containerPort: 8080
          # startupProbe:
          #   httpGet:
          #     path: /geoserver
          #     port: http-geoserver
          #   failureThreshold: 60
          #   periodSeconds: 5
          # livenessProbe:
          #   httpGet:
          #     path: /geoserver
          #     port: http-geoserver
          #     scheme: HTTP
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          #   successThreshold: 1
          #   failureThreshold: 3
          # readinessProbe:
          #   httpGet:
          #     path: /geoserver
          #     port: http-geoserver
          #     scheme: HTTP
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          #   successThreshold: 1
          #   failureThreshold: 3
          volumeMounts:
            - name: geoserver-data-dir
              mountPath: /opt/geoserver/data_dir
            - name: geowebcache-cache-dir
              mountPath: /opt/geoserver/data_dir/gwc
            # - name: geoserver-extensions
            #   mountPath: /usr/local/tomcat/webapps/geoserver/WEB-INF/lib/
          resources:
            requests:
              memory: "30Gi"
              cpu: "4000m"
            limits:
              memory: "100Gi"
              cpu: "30000m"
      volumes:
        - name: geoserver-data-dir
          persistentVolumeClaim:
            claimName: geoserver-data-dir-pvc
        - name: geowebcache-cache-dir
          persistentVolumeClaim:
            claimName: geowebcache-cache-dir-pvc
        # - name: geoserver-extensions
        #   persistentVolumeClaim:
        #     claimName: geoserver-extensions-pvc
