apiVersion: v2
name: geoserver
version: "1.0.13"
appVersion: "2.23.1"
description: Chart for GeoServer
keywords:
  - GeoServer
  - GIS
home: http://geoserver.org
sources:
  - https://github.com/geoserver/geoserver
maintainers:
- email: info@simcube.co.uk
  name: simcube
icon: https://avatars.githubusercontent.com/u/186522?s=280&v=4
dependencies:
  - name: geoserver
    version: 1.0.13
    repository: https://simcubeltd.github.io/simcube-helm-charts/