geoserver:
  geoserverUser: "admin"

  # For prefilled password
  # It will be stored in secret later
  geoserverPassword: "admin"

  # Define this for extra GeoServer environment variables
  extraPodEnv: |
    - name: GEOSERVER_CSRF_DISABLED
      value: "true"


  # This will be evaluated as pod spec
  extraPodSpec: |
    initContainers:
      - name: download-ilots-file
        image: minio/mc
        command: ["/bin/sh", "-c"]
        args:
        - |
          mc cp s3/projet-slums-detection/data-geoserver/MARTINIQUE/2022/ /dossierimage/data_dir/Martinique_2022 && \
          mc cp s3/projet-slums-detection/data-geoserver/ilots/  /dossierimage/data_dir/ilots
        envFrom:
        - secretRef:
            name: env-secrets-slums-detection
        volumeMounts:
        - name: geoserver-data-dir
          mountPath: /dossierimage


  persistence:
    geoserverDataDir:
      enabled: true
      existingClaim: false
      mountPath: /opt/geoserver/data_dir
      subPath: "data_dir"
      size: 8Gi
      storageClass: ""
      accessModes:
        - ReadWriteOnce
      annotations: {}
    geowebcacheCacheDir:
      enabled: false
      existingClaim: false
      mountPath: /opt/geoserver/data_dir/gwc
      subPath: "gwc"
      size: 8Gi
      storageClass: ""
      accessModes:
        - ReadWriteOnce
      annotations: {}
